### PR TITLE
Release v0.1.0

### PR DESCRIPTION
**Pull request by elong0527**
Initiate v0.1.0 release following checklist in #182

### CODE REVIEW

**Comment by elimillera** [comment]
@elong0527 results from windows check https://win-builder.r-project.org/Rgt1a6NqxAW3

**Comment by marlycormar** [comment]
approve

**Comment by jmanitz** [comment]
Approve

**Review by dgkf — APPROVED** [review]
Thanks for all the documentation and QOL updates!

**Pull request merged**
