### PR TITLE
Add parameter to pkg_ref_cache function to change look back interval

### LINKED ISSUE #258: update pkg_ref downloads
See the following discussion for more information: https://github.com/pharmaR/risk_assessment/discussions/268

The risk assessment app pulls download data from the package's first release. Currently, riskmetric pulls the last 1yr. I think we could parameterize the caching of download information so that a user could change the look back interval.

### PR DESCRIPTION
**Pull request by parmsam-pfizer**
- Fixes #258 - adds parameter called n with default of 365 for user to specify number of days to lookback 
- Updates documentation using devtools::document()

### CODE REVIEW

**Review by emilliman5 — APPROVED** [review]

**Review by emilliman5 — APPROVED** [review]

**Comment by parmsam-pfizer** [comment]
Not sure if this is associated with #259. Looks like I'm getting the following warnings for missing documentation:
```
checking for missing documentation entries ... WARNING
  Undocumented code objects:
    'assess_has_bug_reports_url.pkg_ref'
  All user-level objects in a package should have documentation entries.
  See chapter 'Writing R documentation files' in the 'Writing R
  Extensions' manual.

> checking Rd \usage sections ... WARNING
  Undocumented arguments in documentation object 'assess_covr_coverage'
    'x' '...'
 ```
Are these warnings b/c of the code/documentation I updated?

**Comment by emilliman5** [comment]
I think it is related to #259. Once that PR is merged this one and #249 should pass checks.

**Comment by emilliman5** [comment]
this PR is ready to merged. You will need to merge origin/master into this PR, run R-CMD check to update namespace, roxygenate the docs and then push.

**Comment by parmsam-pfizer** [comment]
Sorry, I'm running into a documentation warning that I'm not quite sure how I should resolve. 
```
❯ checking Rd \usage sections ... WARNING
  Undocumented arguments in documentation object 'assess_covr_coverage'
    ‘x’ ‘...’
  
  Undocumented arguments in documentation object 'assess_dependencies'
    ‘x’ ‘...’
  
  Undocumented arguments in documentation object 'assess_downloads_1yr'
    ‘x’ ‘...’
  
  Undocumented arguments in documentation object 'assess_export_help'
    ‘x’ ‘...’
  
  Undocumented arguments in documentation object 'assess_exported_namespace'
    ‘x’ ‘...’
  
  Undocumented arguments in documentation object 'assess_has_bug_reports_url'
    ‘x’ ‘...’
  
  Undocumented arguments in documentation object 'assess_has_maintainer'
    ‘x’ ‘...’
  
  Undocumented arguments in documentation object 'assess_has_news'
    ‘x’ ‘...’
  
  Undocumented arguments in documentation object 'assess_has_source_control'
    ‘x’ ‘...’
  
  Undocumented arguments in documentation object 'assess_has_vignettes'
    ‘x’ ‘...’
  
  Undocumented arguments in documentation object 'assess_has_website'
    ‘x’ ‘...’
  
  Undocumented arguments in documentation object 'assess_last_30_bugs_status'
    ‘x’ ‘...’
  
  Undocumented arguments in documentation object 'assess_license'
    ‘x’ ‘...’
  
  Undocumented arguments in documentation object 'assess_news_current'
    ‘x’ ‘...’
  
  Undocumented arguments in documentation object 'assess_r_cmd_check'
    ‘x’ ‘...’
  
  Undocumented arguments in documentation object 'assess_remote_checks'
    ‘x’ ‘...’
  
  Undocumented arguments in documentation object 'assess_reverse_dependencies'
    ‘x’ ‘...’
  
  Undocumented arguments in documentation object 'assess_size_codebase'
    ‘x’ ‘...’
  
  Functions with \usage entries need to have the appropriate \alias
  entries, and all their arguments documented.
  The \usage entries must correspond to syntactically valid R code.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.
```

**Comment by emilliman5** [comment]
I will clone your PR and take a look today. What you've described should have solved it.

**Comment by emilliman5** [comment]
For me the issue was a mismatch between the package's RoxygenNotes and my local version of roxygen. Updating my local roxygen2 (7.1.3 -> 7.2.3), then devtools::document(), then R CMD check, updated package documentation correctly.

**Pull request merged**
