### PR TITLE
WIP: Release v0.1.2

### LINKED ISSUE #227: CRAN release v0.1.2 - Resolve example running issue
After #223 is merged. We plan to release a version 0.1.2 to CRAN before R/Pharma

### PR DESCRIPTION
**Pull request by dgkf**
closes #227

## Release Overview

- Removing assumption of unavailable bioc packages during testing to make R CMD check more stable on CRAN 

## Release Checklist

- [x] Cut release branch
- [x] Ensure that NEWS has been updated
- [x] Submit to CRAN
- [x] Tag approved package version commit with release tag (`v#.#.#`)
- [ ] Merge any changes needed for release back into `master`
- [x] Create a release on GitHub

### CODE REVIEW

**Comment by dgkf** [comment]
More NOTES after another attempt:

```
Flavor: r-devel-windows-ix86+x86_64
Check: examples, Result: NOTE
  Examples with CPU (user + system) or elapsed time > 10s
                        user system elapsed
  assess_downloads_1yr 13.14   6.41   20.63
```

**Review by elimillera — APPROVED** [review]
Hey @dgkf lgtm.

My first guess is that we are running into a similar issue here that got the package archived. Might be an issue with the environment including/excluding packages unexpectedly. I think if we are working on the containers and the environments we control its fine to remove the parts that run on CRAN. CRAN may not be super happy with that though, they made us justify some use of 'dontrun' in our packages. I think it would be useful to include something in our cran-comments when we submit about this decision.

**Comment by dgkf** [comment]
Thinking about this today, my suspicion is that `available.packages()` might be getting executed on the first example that is run. 

To test this, we can remove the `\dontrun` tags and include a call to `available.packages()` in `.onLoad` such that the repo is already cached when the examples are run.

**Comment by dgkf** [comment]
@elimillera 

> My first guess is that we are running into a similar issue here that got the package archived.

I think this might be different, because a lot of our examples use the `riskmetric` package as the `pkg_ref`, which certainly should be installed locally by the time the examples are being run.

**Comment by elong0527** [comment]
@dgkf , are we ready to release the new version? Or any pending item need to be updated.

**Comment by dgkf** [comment]
@elong0527 - I think it's ready for another round of submissions. However, I never got clear feedback on what exactly is failing with this package. I don't think it's related to changes we made recently. As described above, the working assumption is that `available.packages()` behavior has changed and we are now bearing the cost of first execution in our examples. This is still an assumption, and if this doesn't pan out it's likely going to require further trial and error against the CRAN builder black box. 

The first round of trial and error took quite a lot of time and didn't work out, and I'm not sure I can devote the same investment in another submission. I would appreciate being able to step back from the maintainer role since I've taken a back seat in development for quite a while now.

**Comment by elimillera** [comment]
Hey all, Update on this. I've send this out to CRAN again. They didn't respond to my email regarding the NOTE on the resubmission but I'm keeping my fingers crossed.

**Comment by elimillera** [comment]
CRAN Comments:

> Thanks,
> You have examples for unexported functions.
> Please either omit these examples or export these functions.
> Used ::: in documentation:
>       man/suppressMatchingConditions.Rd:
>          riskmetric:::suppressMatchingConditions({
>   print(paste(letters[1:3], collapse = ", "))
>   warning(structure(list(message = "easy as", call = NULL), class = c("custom_warning", "warning", "condition")))
>   message(paste(1:3, collapse = ", "))
>   message("simple as")
>   warning("do re mi")
> }, message = "d", custom_warning = "as$", warning = "w{2}s")
> 
> You are using installed.packages():
> "This needs to read several files per installed package, which will be slow on Windows and on some network-mounted file systems.
> It will be slow when thousands of packages are installed, so do not use it to find out if a named package is installed (use find.package or
> system.file) nor to find out if a package is usable (call requireNamespace or require and check the return value) nor to find details of a small number of packages (use packageDescription)."
> [installed.packages() help page]
> 
>
> 
> Please fix and resubmit.
> 
> Best,
> Gregor Seyer

@dgkf @elong0527 I've removed the `memoise_installed_packages` functoin and replaced it with `find.package` when checking for an appropriate pkg_ref class. This was the only place we were looking into it so it should be ok. It's off to Rhub now for windows checks and I'll submit again if that all looks good.

**Comment by elimillera** [comment]
This is on its way to CRAN

**Comment by elong0527** [comment]
👍 May I buy you a coffee?

**Comment by elimillera** [comment]
Haha thanks @elong0527, Happy to help no coffee required 😄. riskmetric is published with 0.1.2 and release has been created on github, this is good to merge in

**Pull request merged**
